const state = { scan: null, selected: new Set() };
const $ = (selector) => document.querySelector(selector);
const formatBytes = (bytes) => { const units = ['B','KB','MB','GB','TB']; let value = Math.max(0, bytes); let i = 0; while (value >= 1024 && i < units.length - 1) { value /= 1024; i++; } return `${value.toFixed(i ? 1 : 0)} ${units[i]}`; };

function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); }
function navigate(view) { document.querySelectorAll('.view').forEach((item) => item.classList.toggle('active-view', item.id === view)); if (view === 'recycle') scanRecycleBin(); }
function renderCategories(categories) { const grid = $('#category-grid'); grid.innerHTML = categories.map((category) => `<article class="category-card"><label><input type="checkbox" data-target="${category.id}" aria-label="Select ${category.name}"> Select</label><div class="category-icon">✦</div><h3>${category.name}</h3><p class="muted">${category.file_count.toLocaleString()} files · ${category.safety === 'safe' ? 'Safe to clean' : 'Review required'}</p><strong>${formatBytes(category.size)}</strong><p class="muted">${category.location}</p></article>`).join(''); grid.querySelectorAll('input').forEach((input) => input.addEventListener('change', () => { input.checked ? state.selected.add(input.dataset.target) : state.selected.delete(input.dataset.target); $('#clean-button').disabled = state.selected.size === 0; })); }
function renderReviewItems(items) { const list = $('#review-list'); list.innerHTML = items.length ? items.map((item) => `<li><span>${item.is_directory ? 'Folder' : 'File'}</span><strong>${item.path} · ${formatBytes(item.size)}</strong></li>`).join('') : '<li>No files were found in the approved target.</li>'; }
async function scanRecycleBin() { const buttons = ['#recycle-scan-button', '#recycle-scan-cta']; buttons.forEach((selector) => { const button = $(selector); if (button) { button.disabled = true; button.textContent = 'Scanning...'; } }); try { const response = await fetch('/api/recycle-bin'); const data = await response.json(); $('#recycle-size').textContent = formatBytes(data.total_size); $('#recycle-summary').textContent = `${data.item_count.toLocaleString()} items · Space calculated`; $('#recycle-clean-cta').hidden = data.item_count === 0 || !data.supported; $('#recycle-detail-size').textContent = formatBytes(data.total_size); $('#recycle-detail-count').textContent = `${data.item_count.toLocaleString()} items currently in the Windows Recycle Bin`; $('#empty-recycle-button').disabled = data.item_count === 0 || !data.supported; } catch { showToast('Recycle Bin scan failed'); } finally { const tileButton = $('#recycle-scan-cta'); if (tileButton) { tileButton.disabled = false; tileButton.textContent = 'Rescan'; } const pageButton = $('#recycle-scan-button'); if (pageButton) { pageButton.disabled = false; pageButton.textContent = 'Scan Recycle Bin'; } } }
function openCleanupModal() { $('#cleanup-confirm-size').textContent = $('#recycle-size').textContent; $('#cleanup-modal').hidden = false; }
async function confirmCleanup() { $('#cleanup-modal').hidden = true; await emptyRecycleBin(true); }
async function emptyRecycleBin(skipConfirm = false) { const size = $('#recycle-detail-size').textContent; if (!skipConfirm && !confirm(`Empty Recycle Bin? This permanently deletes ${size} of files.`)) return; const response = await fetch('/api/recycle-bin/empty', { method: 'POST' }); const result = await response.json(); if (!response.ok) { showToast(result.detail || 'Could not empty Recycle Bin'); return; } showToast('Recycle Bin emptied.'); await scanRecycleBin(); }
async function cleanSelected() { if (!state.selected.size || !confirm(`Clean ${state.selected.size} selected target(s)? Files will be removed only after this confirmation.`)) return; const response = await fetch('/api/cleanup', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ targets: [...state.selected] }) }); const result = await response.json(); if (!response.ok) { showToast(result.detail || 'Cleanup failed'); return; } showToast(`${formatBytes(result.bytes_removed)} recovered; ${result.files_skipped} skipped.`); state.selected.clear(); $('#clean-button').disabled = true; await scan(); }
async function loadStorage() { try { const response = await fetch('/api/system/storage'); const data = await response.json(); const usedPercent = data.total ? Math.round(data.used / data.total * 100) : 0; $('#storage-title').textContent = `${data.path} drive`; $('#storage-subtitle').textContent = `${formatBytes(data.free)} free of ${formatBytes(data.total)}`; $('#storage-percent').textContent = `${usedPercent}%`; } catch { $('#storage-subtitle').textContent = 'Storage information unavailable'; } }
async function scan() { const button = $('#scan-button'); button.disabled = true; button.textContent = 'Scanning...'; $('#scan-message').textContent = 'Checking approved temporary locations...'; try { const response = await fetch('/api/scan', { method: 'POST' }); if (!response.ok) throw new Error('Scan failed'); state.scan = await response.json(); $('#cleanable-size').textContent = formatBytes(state.scan.total_size); $('#file-count').textContent = state.scan.total_files.toLocaleString(); $('#scan-message').textContent = 'Review the categories below before cleanup.'; $('#last-scan-status').textContent = 'Completed just now'; renderCategories(state.scan.categories); renderReviewItems(state.scan.categories.flatMap((category) => category.items || [])); showToast('Scan complete. Nothing was deleted.'); } catch (error) { showToast(error.message); } finally { button.disabled = false; button.innerHTML = 'Scan now <span>→</span>'; } }
document.querySelectorAll('[data-view]').forEach((item) => item.addEventListener('click', () => navigate(item.dataset.view)));
$('#scan-button').addEventListener('click', scan); $('#clean-button').addEventListener('click', cleanSelected); loadStorage();
$('#recycle-scan-button').addEventListener('click', scanRecycleBin); $('#empty-recycle-button').addEventListener('click', emptyRecycleBin);
$('#recycle-scan-cta').addEventListener('click', scanRecycleBin); $('#recycle-clean-cta').addEventListener('click', openCleanupModal); $('#cancel-cleanup').addEventListener('click', () => { $('#cleanup-modal').hidden = true; }); $('#confirm-cleanup').addEventListener('click', confirmCleanup);
